"""question types branching nps

Revision ID: 28959119f653
Revises: 77dc4c391f86
Create Date: 2026-09-26 08:07:11.552594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28959119f653'
down_revision = '77dc4c391f86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE question_type_enum ADD VALUE IF NOT EXISTS 'choice'")
        op.execute("ALTER TYPE question_type_enum ADD VALUE IF NOT EXISTS 'nps'")
    op.add_column('question', sa.Column('help_text', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('question', sa.Column('allow_multiple', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('question', sa.Column('show_if_question_id', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('show_if_operator', sa.String(length=5), nullable=True))
    op.add_column('question', sa.Column('show_if_value', sa.String(length=100), nullable=True))
    op.create_foreign_key('fk_question_show_if', 'question', 'question', ['show_if_question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_question_show_if', 'question', type_='foreignkey')
    op.drop_column('question', 'show_if_value')
    op.drop_column('question', 'show_if_operator')
    op.drop_column('question', 'show_if_question_id')
    op.drop_column('question', 'allow_multiple')
    op.drop_column('question', 'options')
    op.drop_column('question', 'help_text')
    # ### end Alembic commands ###
