"""add login_code table

Revision ID: 392d1e8211a3
Revises: 55598617b720
Create Date: 2026-09-25 23:18:20.016399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392d1e8211a3'
down_revision = '55598617b720'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_code_person_id'), 'login_code', ['person_id'], unique=False)
    op.create_index(op.f('ix_login_code_round_id'), 'login_code', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_code_round_id'), table_name='login_code')
    op.drop_index(op.f('ix_login_code_person_id'), table_name='login_code')
    op.drop_table('login_code')
    # ### end Alembic commands ###
