"""initial schema

Revision ID: 55598617b720
Revises: 
Create Date: 2026-09-25 22:17:57.087731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55598617b720'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('org_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('fachbereich', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_org_unit_fachbereich'), 'org_unit', ['fachbereich'], unique=False)
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('survey_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personalnummer', sa.String(length=50), nullable=False),
    sa.Column('vorname', sa.String(length=200), nullable=False),
    sa.Column('nachname', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('org_unit_id', sa.Integer(), nullable=True),
    sa.Column('manager_personalnummer', sa.String(length=50), nullable=True),
    sa.Column('standort', sa.String(length=200), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_manager_personalnummer'), 'person', ['manager_personalnummer'], unique=False)
    op.create_index(op.f('ix_person_personalnummer'), 'person', ['personalnummer'], unique=True)
    op.create_table('survey_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_template_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('entwurf', 'gesperrt', name='survey_version_status_enum'), nullable=False),
    sa.Column('limesurvey_template_sid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_template_id'], ['survey_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_version_survey_template_id'), 'survey_version', ['survey_template_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_person_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_version_id'], ['survey_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimension_survey_version_id'), 'dimension', ['survey_version_id'], unique=False)
    op.create_table('role_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'fuehrungskraft', 'mitarbeiter', name='role_enum'), nullable=False),
    sa.Column('assigned_by_person_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_assignment_person_id'), 'role_assignment', ['person_id'], unique=False)
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('survey_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('entwurf', 'geplant', 'offen', 'geschlossen', 'ausgewertet', 'berichtet', name='round_status_enum'), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminder_days_before_end', sa.JSON(), nullable=False),
    sa.Column('report_channel', sa.Enum('portal', 'email', 'beides', name='report_channel_enum'), nullable=False),
    sa.Column('target_fachbereiche', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_version_id'], ['survey_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round_survey_version_id'), 'round', ['survey_version_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_person_id'), 'notification', ['person_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_version_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('likert', 'freitext', name='question_type_enum'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('scale_min', sa.Integer(), nullable=True),
    sa.Column('scale_max', sa.Integer(), nullable=True),
    sa.Column('pole_label_min', sa.String(length=200), nullable=True),
    sa.Column('pole_label_max', sa.String(length=200), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('limesurvey_question_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimension.id'], ),
    sa.ForeignKeyConstraint(['survey_version_id'], ['survey_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_survey_version_id'), 'question', ['survey_version_id'], unique=False)
    op.create_table('round_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('leader_person_id', sa.Integer(), nullable=False),
    sa.Column('leader_code', sa.String(length=50), nullable=False),
    sa.Column('limesurvey_sid', sa.Integer(), nullable=True),
    sa.Column('team_size_snapshot', sa.Integer(), nullable=False),
    sa.Column('evaluable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leader_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leader_code')
    )
    op.create_index(op.f('ix_round_target_leader_person_id'), 'round_target', ['leader_person_id'], unique=False)
    op.create_index(op.f('ix_round_target_round_id'), 'round_target', ['round_id'], unique=False)
    op.create_table('participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('round_target_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('offen', 'erledigt', name='participation_status_enum'), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('limesurvey_token', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.ForeignKeyConstraint(['round_target_id'], ['round_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participation_person_id'), 'participation', ['person_id'], unique=False)
    op.create_index(op.f('ix_participation_round_id'), 'participation', ['round_id'], unique=False)
    op.create_index(op.f('ix_participation_round_target_id'), 'participation', ['round_target_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_target_id', sa.Integer(), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_target_id'], ['round_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_round_target_id'), 'report', ['round_target_id'], unique=True)
    op.create_table('result_aggregate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_target_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('dimension_id', sa.Integer(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('median', sa.Float(), nullable=True),
    sa.Column('stddev', sa.Float(), nullable=True),
    sa.Column('distribution', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimension.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['round_target_id'], ['round_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_aggregate_round_target_id'), 'result_aggregate', ['round_target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_aggregate_round_target_id'), table_name='result_aggregate')
    op.drop_table('result_aggregate')
    op.drop_index(op.f('ix_report_round_target_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_participation_round_target_id'), table_name='participation')
    op.drop_index(op.f('ix_participation_round_id'), table_name='participation')
    op.drop_index(op.f('ix_participation_person_id'), table_name='participation')
    op.drop_table('participation')
    op.drop_index(op.f('ix_round_target_round_id'), table_name='round_target')
    op.drop_index(op.f('ix_round_target_leader_person_id'), table_name='round_target')
    op.drop_table('round_target')
    op.drop_index(op.f('ix_question_survey_version_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_notification_person_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_round_survey_version_id'), table_name='round')
    op.drop_table('round')
    op.drop_index(op.f('ix_role_assignment_person_id'), table_name='role_assignment')
    op.drop_table('role_assignment')
    op.drop_index(op.f('ix_dimension_survey_version_id'), table_name='dimension')
    op.drop_table('dimension')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_survey_version_survey_template_id'), table_name='survey_version')
    op.drop_table('survey_version')
    op.drop_index(op.f('ix_person_personalnummer'), table_name='person')
    op.drop_index(op.f('ix_person_manager_personalnummer'), table_name='person')
    op.drop_table('person')
    op.drop_table('survey_template')
    op.drop_table('setting')
    op.drop_index(op.f('ix_org_unit_fachbereich'), table_name='org_unit')
    op.drop_table('org_unit')
    op.drop_table('mail_template')
    op.drop_table('import_log')
    # ### end Alembic commands ###
