"""report freetext

Revision ID: 77dc4c391f86
Revises: 392d1e8211a3
Create Date: 2026-09-26 02:20:26.199845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77dc4c391f86'
down_revision = '392d1e8211a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('freetext', sa.JSON(), nullable=True))
    op.add_column('report', sa.Column('n_responses', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('suppressed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'suppressed')
    op.drop_column('report', 'n_responses')
    op.drop_column('report', 'freetext')
    # ### end Alembic commands ###
